[package]
name = "screenshot_gnome"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_12"] }
libadwaita = { version = "0.7", features = ["v1_5"] }
xcap = "0.0.14"
image = "0.25"
