[package]
name = "screenshot_gnome"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.10", features = ["v4_12"] }
libadwaita = { version = "0.8", features = ["v1_5"] }
xcap = "0.4"
image = "0.25"
