[package]
name = "screenshot_gnome"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.10.3", features = ["v4_12"] }
image = "0.25.9"
libadwaita = { version = "0.8.1", features = ["v1_5"] }
xcap = "0.8.0"
log = "0.4"
env_logger = "0.11"
